name: Deploy Nuget packages

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '6.0'
  PACKAGE_VERSION: "0.8.2"

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: |
          dotnet restore Firepuma.CommandsAndQueries.Abstractions
          dotnet restore Firepuma.CommandsAndQueries.CosmosDb
          dotnet restore Firepuma.CommandsAndQueries.MongoDb
          dotnet restore Firepuma.CommandsAndQueries.Tests

      - name: Test
        run: dotnet test --no-restore

      - name: Package
        run: |
          dotnet pack --configuration Release --output . -p:PackageVersion=${{ env.PACKAGE_VERSION }} Firepuma.CommandsAndQueries.Abstractions/Firepuma.CommandsAndQueries.Abstractions.csproj
          dotnet pack --configuration Release --output . -p:PackageVersion=${{ env.PACKAGE_VERSION }} Firepuma.CommandsAndQueries.CosmosDb/Firepuma.CommandsAndQueries.CosmosDb.csproj
          dotnet pack --configuration Release --output . -p:PackageVersion=${{ env.PACKAGE_VERSION }} Firepuma.CommandsAndQueries.MongoDb/Firepuma.CommandsAndQueries.MongoDb.csproj

      - name: Publish
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
